//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiRep.Web.HinaOrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GlobalPatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientMasterIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpellNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocietyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClinicalNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InpatientNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        private System.Guid MergeIdField;
        
        private System.Guid HospitalIdField;
        
        private System.DateTime LastUpdateDateTimeField;
        
        private System.Nullable<System.DateTime> CreateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarriageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FamilyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GivenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HISPatientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNodeField;
        
        private bool IsDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateUserDescField;
        
        private System.Nullable<System.DateTime> UpdateDateField;
        
        private MultiRep.Web.HinaOrderService.TimeSpan UpdateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string GlobalPatientId {
            get {
                return this.GlobalPatientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GlobalPatientIdField, value) != true)) {
                    this.GlobalPatientIdField = value;
                    this.RaisePropertyChanged("GlobalPatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PatientMasterIndex {
            get {
                return this.PatientMasterIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientMasterIndexField, value) != true)) {
                    this.PatientMasterIndexField = value;
                    this.RaisePropertyChanged("PatientMasterIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SpellName {
            get {
                return this.SpellNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpellNameField, value) != true)) {
                    this.SpellNameField = value;
                    this.RaisePropertyChanged("SpellName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SocietyNumber {
            get {
                return this.SocietyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SocietyNumberField, value) != true)) {
                    this.SocietyNumberField = value;
                    this.RaisePropertyChanged("SocietyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ClinicalNumber {
            get {
                return this.ClinicalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClinicalNumberField, value) != true)) {
                    this.ClinicalNumberField = value;
                    this.RaisePropertyChanged("ClinicalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string InpatientNumber {
            get {
                return this.InpatientNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InpatientNumberField, value) != true)) {
                    this.InpatientNumberField = value;
                    this.RaisePropertyChanged("InpatientNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string NationName {
            get {
                return this.NationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NationNameField, value) != true)) {
                    this.NationNameField = value;
                    this.RaisePropertyChanged("NationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Guid MergeId {
            get {
                return this.MergeIdField;
            }
            set {
                if ((this.MergeIdField.Equals(value) != true)) {
                    this.MergeIdField = value;
                    this.RaisePropertyChanged("MergeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Guid HospitalId {
            get {
                return this.HospitalIdField;
            }
            set {
                if ((this.HospitalIdField.Equals(value) != true)) {
                    this.HospitalIdField = value;
                    this.RaisePropertyChanged("HospitalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.DateTime LastUpdateDateTime {
            get {
                return this.LastUpdateDateTimeField;
            }
            set {
                if ((this.LastUpdateDateTimeField.Equals(value) != true)) {
                    this.LastUpdateDateTimeField = value;
                    this.RaisePropertyChanged("LastUpdateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<System.DateTime> CreateDateTime {
            get {
                return this.CreateDateTimeField;
            }
            set {
                if ((this.CreateDateTimeField.Equals(value) != true)) {
                    this.CreateDateTimeField = value;
                    this.RaisePropertyChanged("CreateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string IDCard {
            get {
                return this.IDCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCardField, value) != true)) {
                    this.IDCardField = value;
                    this.RaisePropertyChanged("IDCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Marriage {
            get {
                return this.MarriageField;
            }
            set {
                if ((object.ReferenceEquals(this.MarriageField, value) != true)) {
                    this.MarriageField = value;
                    this.RaisePropertyChanged("Marriage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string FamilyName {
            get {
                return this.FamilyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilyNameField, value) != true)) {
                    this.FamilyNameField = value;
                    this.RaisePropertyChanged("FamilyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string GivenName {
            get {
                return this.GivenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GivenNameField, value) != true)) {
                    this.GivenNameField = value;
                    this.RaisePropertyChanged("GivenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string HISPatientId {
            get {
                return this.HISPatientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.HISPatientIdField, value) != true)) {
                    this.HISPatientIdField = value;
                    this.RaisePropertyChanged("HISPatientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ServerNode {
            get {
                return this.ServerNodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNodeField, value) != true)) {
                    this.ServerNodeField = value;
                    this.RaisePropertyChanged("ServerNode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public bool IsDelete {
            get {
                return this.IsDeleteField;
            }
            set {
                if ((this.IsDeleteField.Equals(value) != true)) {
                    this.IsDeleteField = value;
                    this.RaisePropertyChanged("IsDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string UpdateUserCode {
            get {
                return this.UpdateUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateUserCodeField, value) != true)) {
                    this.UpdateUserCodeField = value;
                    this.RaisePropertyChanged("UpdateUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string UpdateUserDesc {
            get {
                return this.UpdateUserDescField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateUserDescField, value) != true)) {
                    this.UpdateUserDescField = value;
                    this.RaisePropertyChanged("UpdateUserDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((this.UpdateDateField.Equals(value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public MultiRep.Web.HinaOrderService.TimeSpan UpdateTime {
            get {
                return this.UpdateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateTimeField, value) != true)) {
                    this.UpdateTimeField = value;
                    this.RaisePropertyChanged("UpdateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSpan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TimeSpan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HinaOrderService.PlatformInterfaceServiceSoap")]
    public interface PlatformInterfaceServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MultiRep.Web.HinaOrderService.HelloWorldResponse HelloWorld(MultiRep.Web.HinaOrderService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.HelloWorldResponse> HelloWorldAsync(MultiRep.Web.HinaOrderService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TestDBResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDB", ReplyAction="*")]
        MultiRep.Web.HinaOrderService.TestDBResponse TestDB(MultiRep.Web.HinaOrderService.TestDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestDB", ReplyAction="*")]
        System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.TestDBResponse> TestDBAsync(MultiRep.Web.HinaOrderService.TestDBRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 PostFailedOrderDataResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostFailedOrderData", ReplyAction="*")]
        MultiRep.Web.HinaOrderService.PostFailedOrderDataResponse PostFailedOrderData(MultiRep.Web.HinaOrderService.PostFailedOrderDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostFailedOrderData", ReplyAction="*")]
        System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.PostFailedOrderDataResponse> PostFailedOrderDataAsync(MultiRep.Web.HinaOrderService.PostFailedOrderDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 action 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HIPMessage", ReplyAction="*")]
        MultiRep.Web.HinaOrderService.HIPMessageResponse HIPMessage(MultiRep.Web.HinaOrderService.HIPMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HIPMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.HIPMessageResponse> HIPMessageAsync(MultiRep.Web.HinaOrderService.HIPMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MultiRep.Web.HinaOrderService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MultiRep.Web.HinaOrderService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MultiRep.Web.HinaOrderService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MultiRep.Web.HinaOrderService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDB", Namespace="http://tempuri.org/", Order=0)]
        public MultiRep.Web.HinaOrderService.TestDBRequestBody Body;
        
        public TestDBRequest() {
        }
        
        public TestDBRequest(MultiRep.Web.HinaOrderService.TestDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestDBRequestBody {
        
        public TestDBRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestDBResponse", Namespace="http://tempuri.org/", Order=0)]
        public MultiRep.Web.HinaOrderService.TestDBResponseBody Body;
        
        public TestDBResponse() {
        }
        
        public TestDBResponse(MultiRep.Web.HinaOrderService.TestDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MultiRep.Web.HinaOrderService.Patient TestDBResult;
        
        public TestDBResponseBody() {
        }
        
        public TestDBResponseBody(MultiRep.Web.HinaOrderService.Patient TestDBResult) {
            this.TestDBResult = TestDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostFailedOrderDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostFailedOrderData", Namespace="http://tempuri.org/", Order=0)]
        public MultiRep.Web.HinaOrderService.PostFailedOrderDataRequestBody Body;
        
        public PostFailedOrderDataRequest() {
        }
        
        public PostFailedOrderDataRequest(MultiRep.Web.HinaOrderService.PostFailedOrderDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PostFailedOrderDataRequestBody {
        
        public PostFailedOrderDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostFailedOrderDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostFailedOrderDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public MultiRep.Web.HinaOrderService.PostFailedOrderDataResponseBody Body;
        
        public PostFailedOrderDataResponse() {
        }
        
        public PostFailedOrderDataResponse(MultiRep.Web.HinaOrderService.PostFailedOrderDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostFailedOrderDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostFailedOrderDataResult;
        
        public PostFailedOrderDataResponseBody() {
        }
        
        public PostFailedOrderDataResponseBody(string PostFailedOrderDataResult) {
            this.PostFailedOrderDataResult = PostFailedOrderDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HIPMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HIPMessage", Namespace="http://tempuri.org/", Order=0)]
        public MultiRep.Web.HinaOrderService.HIPMessageRequestBody Body;
        
        public HIPMessageRequest() {
        }
        
        public HIPMessageRequest(MultiRep.Web.HinaOrderService.HIPMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HIPMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string action;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        public HIPMessageRequestBody() {
        }
        
        public HIPMessageRequestBody(string action, string message) {
            this.action = action;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HIPMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HIPMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public MultiRep.Web.HinaOrderService.HIPMessageResponseBody Body;
        
        public HIPMessageResponse() {
        }
        
        public HIPMessageResponse(MultiRep.Web.HinaOrderService.HIPMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HIPMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HIPMessageResult;
        
        public HIPMessageResponseBody() {
        }
        
        public HIPMessageResponseBody(string HIPMessageResult) {
            this.HIPMessageResult = HIPMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlatformInterfaceServiceSoapChannel : MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlatformInterfaceServiceSoapClient : System.ServiceModel.ClientBase<MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap>, MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap {
        
        public PlatformInterfaceServiceSoapClient() {
        }
        
        public PlatformInterfaceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlatformInterfaceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformInterfaceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformInterfaceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultiRep.Web.HinaOrderService.HelloWorldResponse MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap.HelloWorld(MultiRep.Web.HinaOrderService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MultiRep.Web.HinaOrderService.HelloWorldRequest inValue = new MultiRep.Web.HinaOrderService.HelloWorldRequest();
            inValue.Body = new MultiRep.Web.HinaOrderService.HelloWorldRequestBody();
            MultiRep.Web.HinaOrderService.HelloWorldResponse retVal = ((MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.HelloWorldResponse> MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap.HelloWorldAsync(MultiRep.Web.HinaOrderService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.HelloWorldResponse> HelloWorldAsync() {
            MultiRep.Web.HinaOrderService.HelloWorldRequest inValue = new MultiRep.Web.HinaOrderService.HelloWorldRequest();
            inValue.Body = new MultiRep.Web.HinaOrderService.HelloWorldRequestBody();
            return ((MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultiRep.Web.HinaOrderService.TestDBResponse MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap.TestDB(MultiRep.Web.HinaOrderService.TestDBRequest request) {
            return base.Channel.TestDB(request);
        }
        
        public MultiRep.Web.HinaOrderService.Patient TestDB() {
            MultiRep.Web.HinaOrderService.TestDBRequest inValue = new MultiRep.Web.HinaOrderService.TestDBRequest();
            inValue.Body = new MultiRep.Web.HinaOrderService.TestDBRequestBody();
            MultiRep.Web.HinaOrderService.TestDBResponse retVal = ((MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap)(this)).TestDB(inValue);
            return retVal.Body.TestDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.TestDBResponse> MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap.TestDBAsync(MultiRep.Web.HinaOrderService.TestDBRequest request) {
            return base.Channel.TestDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.TestDBResponse> TestDBAsync() {
            MultiRep.Web.HinaOrderService.TestDBRequest inValue = new MultiRep.Web.HinaOrderService.TestDBRequest();
            inValue.Body = new MultiRep.Web.HinaOrderService.TestDBRequestBody();
            return ((MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap)(this)).TestDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultiRep.Web.HinaOrderService.PostFailedOrderDataResponse MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap.PostFailedOrderData(MultiRep.Web.HinaOrderService.PostFailedOrderDataRequest request) {
            return base.Channel.PostFailedOrderData(request);
        }
        
        public string PostFailedOrderData() {
            MultiRep.Web.HinaOrderService.PostFailedOrderDataRequest inValue = new MultiRep.Web.HinaOrderService.PostFailedOrderDataRequest();
            inValue.Body = new MultiRep.Web.HinaOrderService.PostFailedOrderDataRequestBody();
            MultiRep.Web.HinaOrderService.PostFailedOrderDataResponse retVal = ((MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap)(this)).PostFailedOrderData(inValue);
            return retVal.Body.PostFailedOrderDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.PostFailedOrderDataResponse> MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap.PostFailedOrderDataAsync(MultiRep.Web.HinaOrderService.PostFailedOrderDataRequest request) {
            return base.Channel.PostFailedOrderDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.PostFailedOrderDataResponse> PostFailedOrderDataAsync() {
            MultiRep.Web.HinaOrderService.PostFailedOrderDataRequest inValue = new MultiRep.Web.HinaOrderService.PostFailedOrderDataRequest();
            inValue.Body = new MultiRep.Web.HinaOrderService.PostFailedOrderDataRequestBody();
            return ((MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap)(this)).PostFailedOrderDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MultiRep.Web.HinaOrderService.HIPMessageResponse MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap.HIPMessage(MultiRep.Web.HinaOrderService.HIPMessageRequest request) {
            return base.Channel.HIPMessage(request);
        }
        
        public string HIPMessage(string action, string message) {
            MultiRep.Web.HinaOrderService.HIPMessageRequest inValue = new MultiRep.Web.HinaOrderService.HIPMessageRequest();
            inValue.Body = new MultiRep.Web.HinaOrderService.HIPMessageRequestBody();
            inValue.Body.action = action;
            inValue.Body.message = message;
            MultiRep.Web.HinaOrderService.HIPMessageResponse retVal = ((MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap)(this)).HIPMessage(inValue);
            return retVal.Body.HIPMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.HIPMessageResponse> MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap.HIPMessageAsync(MultiRep.Web.HinaOrderService.HIPMessageRequest request) {
            return base.Channel.HIPMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MultiRep.Web.HinaOrderService.HIPMessageResponse> HIPMessageAsync(string action, string message) {
            MultiRep.Web.HinaOrderService.HIPMessageRequest inValue = new MultiRep.Web.HinaOrderService.HIPMessageRequest();
            inValue.Body = new MultiRep.Web.HinaOrderService.HIPMessageRequestBody();
            inValue.Body.action = action;
            inValue.Body.message = message;
            return ((MultiRep.Web.HinaOrderService.PlatformInterfaceServiceSoap)(this)).HIPMessageAsync(inValue);
        }
    }
}
